### ISSUE TITLE
[Feature]  Add Pre-Chat Tiles for Direct Input Start, Similar to ChatGPT Interface

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/Dev-Exchange#12]
### Description

**I would like to add tiles at the beginning of the chat interface, similar to those in ChatGPT, before the chat session starts. These tiles should function such that when a user clicks on one, the chat session begins directly with that input.**

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/85815172/53c747f5-5d23-498b-b46a-e9f1fbea33ac)

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/85815172/63e1fb89-1fac-4f99-ba30-3afa079e0715)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by ShreyashKathade** [comment]
Can  i work on this issue , i have worked on similar project before.

**Comment by Nishitbaria** [comment]
> Can i work on this issue , i have worked on similar project before.

 **you may work on this issue, but please ensure to adhere to the contribution guidelines as well.**

**Comment by Nishitbaria** [comment]
any update @ShreyashKathade

**Comment by Nishitbaria** [comment]
> any update @ShreyashKathade

Hey @ShreyashKathade You are not responding that vice i am going open this issue for others

**Comment by Nishitbaria** [comment]
@avayyyyyyy Do you want to work on this issue ?

**Comment by avayyyyyyy** [comment]
Yup sure! I'm happy to work on this issue! @Nishitbaria but tomorrow is my interview so I can only make the pull request by tomorrow evening.

**Comment by Nishitbaria** [comment]
> Yup sure! I'm happy to work on this issue! @Nishitbaria but tomorrow is my interview so I can only make the pull request by tomorrow evening.

Yea sure
