### ISSUE TITLE
[BUG]  Greeting GitHub Action workflow is Not working 

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/Dev-Exchange#13]
### Description

Greeting GitHub Action workflow is Not working If any one know what the issue please Fix it 

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/85815172/c693c71b-a8ce-4998-a348-e8b9e51987bf)

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by Vaibhavsg17** [comment]
@Nishitbaria I am willing to work on this issue

**Comment by Nishitbaria** [comment]
Hey @Vaibhavsg17 I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Nishitbaria** [comment]
first, complete this issue then I am assign other issue because its guideline that one person work on one issue at one time
