### ISSUE TITLE
[Feature] fix the Ai Page

### ISSUE THREAD

**Issue by whodivyanshu** [Nishitbaria/Dev-Exchange#14]
### Description

Hey @Nishitbaria 
can I fix the power by AI page 
I will fix the text input box and the ui of that page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @whodivyanshu  Whenever you can issue please add the appropriate title 

can you show me a redesign of the page Based on that I will assign the issue because there is already one similar issue I have created 
checkout this 
#12

**Comment by whodivyanshu** [comment]
ohh Sorry,
I was doing the same thing like taking inspiration from ChatGPT and applying that here 
so can i do that ?

**Comment by whodivyanshu** [comment]
also I wanted to ask that what if someone is working on that task so can i also work on that
what if I complete the task before him there my PR will get merged or not ?

**Comment by Nishitbaria** [comment]
> also I wanted to ask that what if someone is working on that task so can i also work on that
> what if I complete the task before him there my PR will get merged or not ?
> 

No ,  read contribution.md there all the rule are written

**Comment by Nishitbaria** [comment]
> also I wanted to ask that what if someone is working on that task so can i also work on that
> what if I complete the task before him there my PR will get merged or not ?
> 

If there is any feature in your mind please share here or create issue  I will see if it's align with the project then we going to build that feature.

Happy hacking
