### ISSUE TITLE
[Feature] Share Question Button

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/Dev-Exchange#15]
### Description

**Add one button Where the Link is Copy when the Button is clicked and That Link Redirect that particular Question** 

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/85815172/037da7d8-0f51-46fb-bc71-59fdcb205b98)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Vaibhavsg17** [comment]
@Nishitbaria I am willing to work on this issue

**Comment by thedemonsid** [comment]
Hi @Nishitbaria I am Siddhesh , really liked the work you did on this project and wanted to contribute to it , Also  I have experience with this type of issue and I am willing to work on this issue . Can you assign this issue to me ??

**Comment by Nishitbaria** [comment]
Hey @thedemonsid  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by NotHumanFF** [comment]
Hey @Nishitbaria, upon reviewing this issue, I wanted to contribute to the problem, I have worked on handling dynamic routes and have created some projects before, can you assign me the issue.

**Comment by thedemonsid** [comment]
Hello @Nishitbaria,

I'm currently encountering an issue with the webhook secret key while testing on my local environment. Despite being logged in, I'm unable to store data in the local database. I've been using the webhook secret provided in the Readme.md file, but it doesn't seem to be working.

Do I need to generate and use my own webhook secret, or is there another solution to this problem?

As you can see in the screenshots below, I am logged in:

![User Logged In](https://github.com/Nishitbaria/Dev-Exchange/assets/128967580/3c31c8ec-3f30-4d10-a41e-9beb9849b641.png)

However, I'm receiving the following error:

![Error Message](https://github.com/Nishitbaria/Dev-Exchange/assets/128967580/ea546e64-a036-4f1d-927d-a4e8f37af88f.png)

Any assistance you could provide would be greatly appreciated.

**Comment by Nishitbaria** [comment]
> Hello @Nishitbaria,
> 
> I'm currently encountering an issue with the webhook secret key while testing on my local environment. Despite being logged in, I'm unable to store data in the local database. I've been using the webhook secret provided in the Readme.md file, but it doesn't seem to be working.
> 
> Do I need to generate and use my own webhook secret, or is there another solution to this problem?
> 
> As you can see in the screenshots below, I am logged in:
> 
> ![User Logged In](https://private-user-images.githubusercontent.com/128967580/329807915-3c31c8ec-3f30-4d10-a41e-9beb9849b641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTQ2ODMsIm5iZiI6MTcxNTQ1NDM4MywicGF0aCI6Ii8xMjg5Njc1ODAvMzI5ODA3OTE1LTNjMzFjOGVjLTNmMzAtNGQxMC1hNDFlLTliZWI5ODQ5YjY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxOTA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjFkZTc3NTBiMGUxMzE1MmY0ZGU3NDI0ZWJmNDM2ODg0MGJmMjVhNzE2MjEzMGVkYjVkYTdmZjcyYjNhYmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oDsscoBYvZOMsixT8yZUbHDErW7Bcp2odIWFLzEyR0s)
> 
> However, I'm receiving the following error:
> 
> ![Error Message](https://private-user-images.githubusercontent.com/128967580/329807973-ea546e64-a036-4f1d-927d-a4e8f37af88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTQ2ODMsIm5iZiI6MTcxNTQ1NDM4MywicGF0aCI6Ii8xMjg5Njc1ODAvMzI5ODA3OTczLWVhNTQ2ZTY0LWEwMzYtNGYxZC05MjdkLWE0ZThmMzdhZjg4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxOTA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWQ3MjU4MjNmYTU2NmNlZDUzYTY5MGFiZjEzNWM2ZjFmNjg4ODVjNzA5NWRkZWUwYmE0MjJiNDVmYjlmNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NwIU1c2ToaweCh85e41VQ8mfPAMFCUVNNZj0rxlpIRQ)
> 
> Any assistance you could provide would be greatly appreciated.

It happens because the credential you enter may be wrong user you created using clerk is created in clerk but not in MongoDB

**Comment by Nishitbaria** [comment]
Have you entered the correct MongoDB URL?

**Comment by thedemonsid** [comment]
yeah, The database is created with user and stuff.
![Screenshot from 2024-05-12 01-04-29](https://github.com/Nishitbaria/Dev-Exchange/assets/128967580/69c6fc20-4258-46b8-b603-91e4446d7c5a)
@Nishitbaria

**Comment by Nishitbaria** [comment]
> yeah, The database is created with user and stuff.
> ![Screenshot from 2024-05-12 01-04-29](https://github.com/Nishitbaria/Dev-Exchange/assets/128967580/69c6fc20-4258-46b8-b603-91e4446d7c5a)
> @Nishitbaria 
> 
> 

It's because use not added clerk keys I think and Clerk secret keys

**Comment by thedemonsid** [comment]
hey @Nishitbaria the problem got solved. Needed to use **ngrok for having the server for webhooks url**.Will solve the issue asap

**Comment by thedemonsid** [comment]
@Nishitbaria By mistake unassigned myslelf , can you reassign me ??

**Comment by Nishitbaria** [comment]
Hey @thedemonsid Are you going to work on this issue?

**Comment by Nikhilesh002** [comment]
Hi! I'm Nikhilesh. I want to work on this feature. Please assign me this task with required labels for gssoc24.

**Comment by Nikhilesh002** [comment]
please add labels for gssoc24

**Comment by RashidSiddiqui2004** [comment]
Hi @Nishitbaria👋 , I want to work on this issue, pls assign it to me under GSSOC'24.
