### ISSUE TITLE
[Bug]: Side navigation bar is not showing login button in mobile view

### ISSUE THREAD

**Issue by 01Sriharsha** [Nishitbaria/Dev-Exchange#16]
### Description

- The side navbar is not rendering properly resulting blocked display of login button
- In desktop view and it is working properly, But in mobile view it's not showing.
- Tried with brave and chrome browsers in mobile and faced the same issue

### Screenshots

![Screenshot_20240512-090624](https://github.com/Nishitbaria/Dev-Exchange/assets/102823857/6f741dc7-4d6f-4827-8f7a-9565b2729e3c)

### What browser are you seeing the problem on?

Chrome

**Comment by 01Sriharsha** [comment]
@Nishitbaria Can you assign this issue to me under GSSOC'24? I can update this bug

**Comment by Nishitbaria** [comment]
> @Nishitbaria Can you assign this issue to me under GSSOC'24? I can update this bug

Hey @01Sriharsha  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by 01Sriharsha** [comment]
@Nishitbaria I tried to create a PR. But it failed! What should I do now?

**Comment by Nishitbaria** [comment]
> @Nishitbaria I tried to create a PR. But it failed! What should I do now?

Show me ss what the problem
