### ISSUE TITLE
[BUG] Incorrect Answer Count Displayed on Question Page

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [Nishitbaria/Dev-Exchange#17]
### Description

On the question page of our project, **_there is an issue with the display of the answer count._** The count of answers shown at the top of the page does not accurately reflect the actual number of answers submitted by users. This discrepancy between the displayed count and the actual count of answers leads to confusion and misrepresentation of the question's engagement level.

### Screenshots

For example, on this question page,

actually **_there are only 4 answers, but it displays 8 answers._**

![issue6](https://github.com/Nishitbaria/Dev-Exchange/assets/124426004/2413ca1e-9dca-4177-a111-d1f7b1deb636)

Same issue exists on each question page.

### What browser are you seeing the problem on?

Chrome, Safari, Microsoft Edge

**Comment by RashidSiddiqui2004** [comment]
@Nishitbaria Please assign this task to me under GSSOC'24. 😊✨

**Comment by Nishitbaria** [comment]
> @Nishitbaria Please assign this task to me under GSSOC'24. 😊✨

Hey @RashidSiddiqui2004 I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
