### ISSUE TITLE
[BUG] Community Profile Cards 

### ISSUE THREAD

**Issue by Rohitha-pudu** [Nishitbaria/Dev-Exchange#18]
### Description

The cards are not proper.

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/116823590/a5367dc1-935f-45f4-9077-40860dbeb475)

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by Nishitbaria** [comment]
Hey @Rohitha-pudu  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Rohitha-pudu** [comment]
@Nishitbaria Thank You.I will Start Working on it
