### ISSUE TITLE
[BUG] Cursor Not Updating to Pointer when hovering onto Dark mode

### ISSUE THREAD

**Issue by thedeeppp** [Nishitbaria/Dev-Exchange#25]
### Description

When navigating through the dark mode option in the repository interface, the cursor fails to switch to the pointer icon, making it difficult for users to discern clickable elements. This inconsistency in cursor behavior detracts from the user experience, as users rely on visual cues to interact with interface elements.

below is SS for the same but cursor doesn't show up while taking the screenshot.

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/128926685/cc7965ef-57b3-4132-862a-cb9f4720a76c)

**Comment by thedeeppp** [comment]
Hey, @Nishitbaria this might be a small bug, can you assign this to me under GSSoC

**Comment by notsoocool** [comment]
@Nishitbaria can you assign me this issue as well, as the issue is not fixed yet
