### ISSUE TITLE
[Feature] Integrate shadcn/ui Command component with "Search Globally" component

### ISSUE THREAD

**Issue by SaranshBangar** [Nishitbaria/Dev-Exchange#26]
### Description

Integrating "Command" component with the search bar can make it a one stop shop for the customer

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/114401238/b68ac2ea-99fc-4fcb-89b3-0d0bef718623)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
> ### Description
> The website is missing a footer which would contain all the necessary links
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/114401238/329861781-b68ac2ea-99fc-4fcb-89b3-0d0bef718623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Mjg4MzgsIm5iZiI6MTcxNTUyODUzOCwicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5ODYxNzgxLWI2OGFjMmVhLTk5ZmMtNGZjYi04OWIzLTBkMGJlZjcxODYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNTQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmZhMmMzZTRhN2FlMTA5ODczYTgxMjQyZTdjM2RlNWVmNjY5MmVlOGQyNWJkMDIwOTI2MDcyMWZlNjllMzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C3ioz7PgNge8c6KUFrICCUFOTUyrf_fSrBLFrHhUciE)
> 
> ### Checklist
> * [x]  I have checked the existing issues
> * [x]  I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
> * [x]  I am willing to work on this issue (optional)

Hey @SaranshBangar We don't currently have a Home page for DevExchange I don't think we need a footer on this Link Page

**Comment by Nishitbaria** [comment]
But if you want to create something then you can create This : https://ui.shadcn.com/docs/components/command

**Comment by SaranshBangar** [comment]
Sir should the command component replace the "Search Global" component?

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/114401238/25d19d76-d2f6-4d73-bacf-01c384fbe9fc)

**Comment by Nishitbaria** [comment]
> Sir should the command component replace the "Search Global" component?
> 
> ![image](https://private-user-images.githubusercontent.com/114401238/329862266-25d19d76-d2f6-4d73-bacf-01c384fbe9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjkyNDYsIm5iZiI6MTcxNTUyODk0NiwicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5ODYyMjY2LTI1ZDE5ZDc2LWQyZjYtNGQ3My1iYWNmLTAxYzM4NGZiZTlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNTQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTMwOTYxMmJmZjQ4YmQxZjA4N2QxNTg3MjQyYWI2MTNhYWQzYmE3MDM5MzBiMGNhNGE5YWE0ZDQzNTEyNjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BJUDlPizXysP1HqpJCeqKsDHwIUhbjOSaHjymEj3w5Y)

No can't be replace it but integrate it

**Comment by SaranshBangar** [comment]
Understood sir, I can do that

Should I open a new issue, or can I just continue in this issue?

**Comment by Nishitbaria** [comment]
> Understood sir, I can do that
> 
> Should I open a new issue, or can I just continue in this issue?

Just edit the details

**Comment by SaranshBangar** [comment]
@Nishitbaria sir, I have followed the installation procedure but I am constantly getting the following error message

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/114401238/26c5eb93-a42b-496f-9421-fd3f0330dd4c)

Can you please guide me through it?

**Comment by Nishitbaria** [comment]
> @Nishitbaria sir, I have followed the installation procedure but I am constantly getting the following error message
> 
> ![image](https://private-user-images.githubusercontent.com/114401238/329910307-26c5eb93-a42b-496f-9421-fd3f0330dd4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk0OTAsIm5iZiI6MTcxNTU5OTE5MCwicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5OTEwMzA3LTI2YzVlYjkzLWE0MmItNDk2Zi05NDIxLWZkM2YwMzMwZGQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQzNDM2ZGIyNTEwOGU0NzFhZTlkMWQwYWIyNzFjZjMwMGMyZGJmOGE5YTQ0MTgyMTE5NTIyYjI4NDdjMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QFJycV-jOJQvJk5LI9KJ6crv4Q2U2jSWTQ8S7UzpCN4)
> 
> Can you please guide me through it?



> @Nishitbaria sir, I have followed the installation procedure but I am constantly getting the following error message
> 
> ![image](https://private-user-images.githubusercontent.com/114401238/329910307-26c5eb93-a42b-496f-9421-fd3f0330dd4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk0OTAsIm5iZiI6MTcxNTU5OTE5MCwicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5OTEwMzA3LTI2YzVlYjkzLWE0MmItNDk2Zi05NDIxLWZkM2YwMzMwZGQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQzNDM2ZGIyNTEwOGU0NzFhZTlkMWQwYWIyNzFjZjMwMGMyZGJmOGE5YTQ0MTgyMTE5NTIyYjI4NDdjMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QFJycV-jOJQvJk5LI9KJ6crv4Q2U2jSWTQ8S7UzpCN4)
> 
> Can you please guide me through it?

Let me try

**Comment by notsoocool** [comment]
@SaranshBangar you need to link your Mongo DB connection URL link in .env.local file, then it will not give this error.
