### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Nishitbaria/Dev-Exchange#27]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

**Comment by Nishitbaria** [comment]
@pankaj-bind  Please create an issue with appropriate issue templates

**Comment by avayyyyyyy** [comment]
@Nishitbaria  can i work on this issue?
