### ISSUE TITLE
Missing CONTRIBUTING.md File

### ISSUE THREAD

**Issue by deekshithapalla** [Nishitbaria/Dev-Exchange#28]

**Comment by deekshithapalla** [comment]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Nishitbaria** [comment]
> The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.
> 
> Could you please assign this issue to me under GSSOC 24.

Actully i have created contribution.md but some how i  don't know someone has remove that file but i have added again you can create another issue because we have already contribution.md
