### ISSUE TITLE
[UI Enhancement] - Adding hover effects

### ISSUE THREAD

**Issue by Varad0014** [Nishitbaria/Dev-Exchange#29]
Hey,
Based on the following video, it's noticeable that there are no hover effects on the left sidebar and the filter options. I can add hover effects to these elements, similar to the hover effects already present in the Light/Dark/System theme menu demonstrated in the video. If you find this relevant, please assign this to me under GSSoC 2024.

https://github.com/Nishitbaria/Dev-Exchange/assets/77493105/bae60e49-0c7a-421f-8ab2-f332a5cf2f2f

**Comment by Nishitbaria** [comment]
Hey @Varad0014 Why Did you make PR without assigned issue?

**Comment by Varad0014** [comment]
Hi
Sorry, I was traveling today and wouldn't have been able to make a pull request. I actually completed the task yesterday, so I decided to create the pull request. In the future, I'll ensure to create a pull request only after the issue has been assigned to me.
