### ISSUE TITLE
Feature: Fetch and Display User's GitHub Repositories in Profile

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#31]
We need to implement a feature that allows fetching a user's GitHub repositories using their GitHub username and displaying them on their profile page. This enhancement will provide users with a more personalized and interactive experience on our platform.

Input Field for GitHub Username:

Add an input field in the user profile settings where users can enter their GitHub username.
Fetch Repositories:

Use GitHub's API to fetch the list of public repositories for the given username.
Handle potential errors, such as invalid usernames or API request failures gracefully.
Display Repositories:

On the user's profile page, display a list of their public GitHub repositories.
Include basic details for each repository: repository name, description, stars, forks, and the link to the repository.

ill like to work on this !!

**Comment by Nishitbaria** [comment]
@Sahilll15  Please create an Issue with the appropriate issue template
