### ISSUE TITLE
Integrate Gemini API for Enhancing Questions on Ask Questions Page

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#32]
Integrate the Gemini API on the "Ask Questions" page to enhance the quality of user-submitted questions. The Gemini API provides capabilities beyond grammar correction, including language enhancement, clarity improvement, and context enrichment. By leveraging this API, we can ensure that questions asked on our platform are not only grammatically correct but also well-phrased, clear, and contextually relevant.

**Comment by Nishitbaria** [comment]
@Sahilll15  Please create an Issue with the appropriate issue template
