### ISSUE TITLE
Bug: Bug on question page while answering 

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#34]
#### Description:

{"error":"Cannot read properties of undefined (reading '0')"}

# Steps to Reproduce:
1. Go to the question page.
2. Attempt to answer the question.
3. Observe the error.

#### Expected Behavior:
The error should be properly handled, and if it persists, an error message should be displayed.

#### Additional Information:
It seems like the API might not be receiving the correct input, leading to this error. We need to ensure proper error validation on this page.

**Comment by Nishitbaria** [comment]
Hey @Sahilll15  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Sahilll15** [comment]
@Nishitbaria ig its the problem with the chatGPTs tokens that's causing the issue
 I have implemented the same solution using geminiAPi
have a look at that 
![Screenshot 2024-05-16 at 1 59 55 AM](https://github.com/Nishitbaria/Dev-Exchange/assets/109215419/37c8d99c-cd1a-496b-b045-11e826a6031d)

If you are okay with the implementation we can move ahead with this solution

**Comment by Nishitbaria** [comment]
> #### Description:
> {"error":"Cannot read properties of undefined (reading '0')"}
> 
> # Steps to Reproduce:
> 1. Go to the question page.
> 2. Attempt to answer the question.
> 3. Observe the error.
> 
> #### Expected Behavior:
> The error should be properly handled, and if it persists, an error message should be displayed.
> 
> #### Additional Information:
> It seems like the API might not be receiving the correct input, leading to this error. We need to ensure proper error validation on this page.

I am Okay with Gemini : Use Verser ai SDK for that : https://sdk.vercel.ai/providers/legacy-providers/google
