### ISSUE TITLE
Feature:Leaderboard feature for the most active user on the webiste

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#35]
### Description

Introduce a leaderboard feature to recognize and showcase the most active users on the website. This feature will encourage user engagement, foster a sense of community, and highlight valuable contributions. Users will be ranked based on various metrics such as the number of questions asked, answers provided, likes received, and other relevant interactions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Sahilll15 I am assigning this issue to you

you can start working on this issue

Happy hacking ✨

**Comment by Sahilll15** [comment]
@Nishitbaria  i have completed the PR for this issue bur the PR is not linked can you add the labels for the issue in the PR that will be helpful and close this one as its done
