### ISSUE TITLE
[Feature] Integrate Gemini API for Enhancing Questions on Ask Questions Page

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#36]
### Description

Integrate the Gemini API on the "Ask Questions" page to enhance the quality of user-submitted questions. The Gemini API provides capabilities beyond grammar correction, including language enhancement, clarity improvement, and context enrichment. By leveraging this API, we can ensure that questions asked on our platform are not only grammatically correct but also well-phrased, clear, and contextually relevant.

### Screenshots

On this page
![Screenshot 2024-05-14 at 3 20 51 AM](https://github.com/Nishitbaria/Dev-Exchange/assets/109215419/5f235617-705d-4fad-92b8-1f7464fa08c5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Sahilll15  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
