### ISSUE TITLE
[Feature] Fetch and Display User's GitHub Repositories in Profile

### ISSUE THREAD

**Issue by Sahilll15** [Nishitbaria/Dev-Exchange#37]
### Description

We need to implement a feature that allows fetching a user's GitHub repositories using their GitHub username and displaying them on their profile page. This enhancement will provide users with a more personalized and interactive experience on our platform.

Input Field for GitHub Username:

Add an input field in the user profile settings where users can enter their GitHub username.
Fetch Repositories:

Use GitHub's API to fetch the list of public repositories for the given username.
Handle potential errors, such as invalid usernames or API request failures gracefully.
Display Repositories:

On the user's profile page, display a list of their public GitHub repositories.
Include basic details for each repository: repository name, description, stars, forks, and the link to the repository.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Can you explain Like what you are planning to show on user Profile @Sahilll15

**Comment by Sahilll15** [comment]
@Nishitbaria  I was thinking of fetching the user's GitHub repos and displaying it in his profile using his GitHub username
getting the top repos maybe

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
