### ISSUE TITLE
[BUG] add a tooltip for left menu section in small screen size 

### ISSUE THREAD

**Issue by notsoocool** [Nishitbaria/Dev-Exchange#38]
### Description

A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it when we are in small screen size. So that we can know what is the button for in small screen size.
<img width="567" alt="Screenshot 2024-05-14 at 5 24 18 PM" src="https://github.com/Nishitbaria/Dev-Exchange/assets/35025375/06ec84db-8520-422d-9c59-00e2d615b5b9">
Please assign this issue to me under gssoc 

### What browser are you seeing the problem on?

Safari

**Comment by Nishitbaria** [comment]
Hey @notsoocool  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

Consider following component for Tooltips components : https://ui.shadcn.com/docs/components/tooltip

**Comment by notsoocool** [comment]
issue resolved
