### ISSUE TITLE
[BUG] While Generation Answer using ChatGpt

### ISSUE THREAD

**Issue by CoderSwarup** [Nishitbaria/Dev-Exchange#39]
### Description

There is a bug occurring during the answer generation process using ChatGPT. Users are experiencing interruptions and inconsistencies in the responses generated by the AI. This bug affects the reliability and user experience of the ChatGPT service.

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/128630311/8d3ec36a-44b0-4c60-ac4f-333e70dd6b61)

### Any additional information?

Please Assign me this issue i want to work on it 

### What browser are you seeing the problem on?

Chrome

**Comment by Nishitbaria** [comment]
> There is a bug occurring during the answer generation process using ChatGPT. Users are experiencing interruptions and inconsistencies in the responses generated by the AI. This bug affects the reliability and user experience of the ChatGPT service.

It happens because the Chatgpt API gets an invalid once i will  update it an then it will work again
