### ISSUE TITLE
Missing publishableKey in the README.md

### ISSUE THREAD

**Issue by sriram2k4** [Nishitbaria/Dev-Exchange#42]
### What would you like to share or ask?

<img width="1020" alt="image" src="https://github.com/Nishitbaria/Dev-Exchange/assets/108707179/3bcd645f-3ea6-4157-94b5-8278f2818910">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Its because I update the dependency in project just fetch latest code

**Comment by Nishitbaria** [comment]
Its because i update the dependency in project just fetch latest code
