### ISSUE TITLE
[BUG] Incorrect Redirection on Clicking Author Username in Collections Page Grid

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [Nishitbaria/Dev-Exchange#43]
### Description

Clicking on the **_username or image of an author_** in the grid of posts on the collections page leads to an incorrect redirection, resulting in an unexpected page.

### Screenshots

Here's the screenshot for the wrong re-directed page.

![issue](https://github.com/Nishitbaria/Dev-Exchange/assets/124426004/ef5da5d5-61fe-4bd1-bb5c-134a631d8899)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by RashidSiddiqui2004** [comment]
@Nishitbaria Pls assign this task to me under GSSOC'24.

**Comment by Nishitbaria** [comment]
> @Nishitbaria Pls assign this task to me under GSSOC'24.

I think its not redirect on wrong page its may be some backend issue for now i am assigning the issue if you found any bug in backend then changes it
