### ISSUE TITLE
[BUG] Community Page Card Fixes

### ISSUE THREAD

**Issue by amri-tah** [Nishitbaria/Dev-Exchange#46]
### Description

Some profile cards in the community page doesn't seem to have uniform profile picture sizes. The "No tags Yet" isn't visible either.

Please assign this issue to me as a part of GSSOC '24

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/111682039/2f346f13-72ea-4296-bac6-4c59bb2aa537)

**Comment by Nishitbaria** [comment]
Hey @amri-tah  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Vaibhavtech2006** [comment]
https://github.com/Nishitbaria/Dev-Exchange/issues/46#issuecomment-2115353600
@Nishitbaria assign this work to me i will give definately work on it
