### ISSUE TITLE
[OTHER]Typo in Collection Page title

### ISSUE THREAD

**Issue by Varad0014** [Nishitbaria/Dev-Exchange#49]
### Description
There is a typo in the title for Collection Page. It is written as "Collection Pagew" instead of "Collection Page". If you find this relevant, please assign me this under GSSoC 2024.

### Screenshots
<img width="878" alt="screenshot" src="https://github.com/Nishitbaria/Dev-Exchange/assets/77493105/60102cfd-3d56-4eca-ad50-7c3770d47458">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Varad0014  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
