### ISSUE TITLE
[Feature] Update Scrollbar UI

### ISSUE THREAD

**Issue by anisharma07** [Nishitbaria/Dev-Exchange#59]
### Description

Hey Nishit👋! The UI of scrollbar is not according to the theme of website .... I know some of UI/UX fundamentals and want to update the scrollbar UI matching with the theme of website.. It would be great if you assign me this issue under gssoc 2024

### Screenshots

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/126901961/cd0a64d7-f3e1-41d7-be68-5b6c92dbb4b4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @anisharma07  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
