### ISSUE TITLE
[BUG] In community section some cards are not of same length .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Nishitbaria/Dev-Exchange#62]
### Description

After going to the community tab the cards are shown to be of different length .
![Screenshot 2024-05-18 164324](https://github.com/Nishitbaria/Dev-Exchange/assets/118350936/d74e107f-2487-4616-8cb4-cfacecec310d)

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by Nishitbaria** [comment]
Hey @Ayushmaanagarwal1211  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Ayushmaanagarwal1211** [comment]
Ya Sure .

**Comment by Vaibhavsg17** [comment]
@Nishitbaria this issue is till pending you can assign this to me

**Comment by Vaibhavtech2006** [comment]
@Nishitbaria this issue this is till pending you can assign this to me
