### ISSUE TITLE
[BUG] In  sliding menu, the close button not visible

### ISSUE THREAD

**Issue by anisharma07** [Nishitbaria/Dev-Exchange#63]
### Description

In the mobile, the sliding menu has a black close button, which is not visible in the dark mode.. I can fix it ... Please assign me this issue..

### Screenshots

![WhatsApp Image 2024-05-18 at 22 55 52_4218536c](https://github.com/Nishitbaria/Dev-Exchange/assets/126901961/952ff989-7954-484c-824e-4f3c5ba4b618)

**Comment by Nishitbaria** [comment]
Hey @anisharma07  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
