### ISSUE TITLE
[BUG] Profile Page is improperly formatted.

### ISSUE THREAD

**Issue by bmukesh23** [Nishitbaria/Dev-Exchange#73]
### Description

On mobile screens, the 'Edit Profile' button is not aligned properly, and the user details are also not in the correct aspect ratio.

### Before Fixing the issue:
![Screenshot 2024-05-24 000719](https://github.com/Nishitbaria/Dev-Exchange/assets/127767544/f22ec2c7-6ff3-453c-a68d-1da9dbb3ecbe)

### After Fixing the issue:
![Screenshot 2024-05-24 000737](https://github.com/Nishitbaria/Dev-Exchange/assets/127767544/5f42e4e1-ad6d-483d-9f7f-e15b46128a6f)

### What browser are you seeing the problem on?

Chrome

**Comment by bmukesh23** [comment]
@Nishitbaria assign this to me as a GSSOC'24 contributor :)

**Comment by Nishitbaria** [comment]
Hey @bmukesh23  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
