### ISSUE TITLE
[Feature] Dev Overflow logo is missing in Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [Nishitbaria/Dev-Exchange#75]
### Description

The main logo of the app is not available in mobile screen.
It should be there to promote the name more and let users know what they are using.

![image](https://github.com/Nishitbaria/Dev-Exchange/assets/124615886/53c38102-d3ad-4b4f-a3a0-92f35bc4ee1d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
**Hey @Utsavladia I don't think we need a logo in mobile screen**
