### ISSUE TITLE
[Feature] [BUG] Chat-typing box in the 'Power by AI' is clumsy and needs styling

### ISSUE THREAD

**Issue by mondalsurojit** [Nishitbaria/Dev-Exchange#76]
### Description

Chat-typing box in the 'Power by AI' is clumsy and needs styling. When compared to chat-typing box of popular applications like Whatsapp, our application lacks padding, when the text overflows, moreover the scroll-bar also appears when the text overflows...This in general makes the portion of UI less attractive. Improving this will undoubtedly make it look better :)

### Screenshots

![Screenshot (306)](https://github.com/Nishitbaria/Dev-Exchange/assets/114282267/9650de33-083e-4206-8aab-4319754fac5d)

How Whatsapp handles text overflow...

![Screenshot (307)](https://github.com/Nishitbaria/Dev-Exchange/assets/114282267/2750986a-2e73-4dee-9426-fc5118ab6987)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @mondalsurojit  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
