### ISSUE TITLE
[DOCS] <Add instruction on using GitHub Desktop>

### ISSUE THREAD

**Issue by Priyanshu2631** [Nishitbaria/Dev-Exchange#77]
### Issue Description

I want to update the Contributing.md by adding instructions on how to use Github Desktop and contribute through it. Please assign me this issue under GSSOC'24.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Nishitbaria/Dev-Exchange/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
**Hey @Priyanshu2631  I don't think we need this instruction I will add myself I don' think it is an valid contribution**

**Comment by Nishitbaria** [comment]
Hey @Priyanshu2631  I don't think we need this instruction I will add myself i don' think it is an valid contribution
