### ISSUE TITLE
[Feature] Adding a copywrite section.

### ISSUE THREAD

**Issue by sristy17** [Nishitbaria/Dev-Exchange#79]
### Description

Can add a copywrite section in the navbar?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
> ### Description
> Can add a copywrite section in the navbar?
> 
> ### Screenshots
> _No response_
> 
> ### Checklist
> * [x]  I have checked the existing issues
> * [x]  I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
> * [x]  I am willing to work on this issue (optional)

can you give me an example like what copywriter section you want to implement in navbar ?

**Comment by sristy17** [comment]
![Screenshot from 2024-06-13 19-45-27](https://github.com/Nishitbaria/Dev-Exchange/assets/136837204/7337bd98-37c4-4a0c-b391-97a8c4228897)
![Screenshot from 2024-06-13 19-52-01](https://github.com/Nishitbaria/Dev-Exchange/assets/136837204/da0665f7-19de-4e9e-93f8-f5b673d89939)


We can add this kind of copywrite section in the bottom of  either of the navbars.

**Comment by Nishitbaria** [comment]
It's not needed  @sristy17
