### ISSUE TITLE
[BUG] Replace "Start new chat" button

### ISSUE THREAD

**Issue by LolPanda7154** [Nishitbaria/Dev-Exchange#83]
### Description

It is placed in top of the input prompt and when we click the button, it clears the chat leading to wrong misguidance. Instead it can be placed right to input prompt and changed as "clear chat". Mainly because it performs that funtion.

### Screenshots

![issue2](https://github.com/Nishitbaria/Dev-Exchange/assets/98698654/0eb8a6a7-eff7-4b42-9cbe-d7dfe9d51491)

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by Nishitbaria** [comment]
Hey @lolpanda2004  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
