### ISSUE TITLE
[Feature] Add scroll to up button

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Nishitbaria/Dev-Exchange#85]
### Description

I want to add scroll to up button

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
can you explain what it helps me in this app @VaishnaviMankala19 ?
