### ISSUE TITLE
[Feature] Adding a footer to the website

### ISSUE THREAD

**Issue by Rajul-29** [Nishitbaria/Dev-Exchange#87]
### Description

Adding a footer will allow us to include copyright information, enhance the look of the website and help in navigation

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Rajul-29** [comment]
Hey @Nishitbaria!
Can you assign me this issue under GSSOC'24
Thank you

**Comment by Nishitbaria** [comment]
Its not needed in website @Rajul-29
