### ISSUE TITLE
[Feature] kubernetes Your app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [Nishitbaria/Dev-Exchange#88]
### Description

As your app is dockerize then we can wrap up your app with kubernetes so that your app have many pods which can load balancing your website and also self healf your website and also kubernetes helps in update the code when code is live

### Screenshots

no screenshot needed

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
What can you do means explain in more details @agarwalhimanshugaya

**Comment by agarwalhimanshugaya** [comment]
@Nishitbaria Sr i push docker image on dockerhub then using that image i write deployment.yaml and service.yaml file thrugh which user can deploy the app locally with load balancer and many more benefits

**Comment by Nishitbaria** [comment]
> @Nishitbaria Sr i push docker image on dockerhub then using that image i write deployment.yaml and service.yaml file thrugh which user can deploy the app locally with load balancer and many more benefits

Hey there any update ?

**Comment by agarwalhimanshugaya** [comment]
@Nishitbaria yes sr i will complete in one day

**Comment by agarwalhimanshugaya** [comment]
@Nishitbaria kindly accpt this pr because after 31st july it is not considered for gssoc

**Comment by agarwalhimanshugaya** [comment]
@Nishitbaria sr plz add label in pr so that it is counted in gssoc
