### ISSUE TITLE
[Feature] add a contact us page

### ISSUE THREAD

**Issue by AbhishiktaRay03** [Nishitbaria/Dev-Exchange#89]
### Description

contacting the autors of website is important

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Its not needed in project @AbhishiktaRay03
